# Generated by Django 5.0.3 on 2024-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('camera', models.CharField(max_length=100)),
                ('storage_ram', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('android_version', models.CharField(max_length=100)),
                ('sim_type', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=100)),
            ],
        ),
    ]
